// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUotSKCurCowo5Hs1Wphu79VBUBySXGlI',
    appId: '1:939353486689:web:5bf1908c44cebefbc0c120',
    messagingSenderId: '939353486689',
    projectId: 'prjpab2-si61-0036',
    authDomain: 'prjpab2-si61-0036.firebaseapp.com',
    storageBucket: 'prjpab2-si61-0036.firebasestorage.app',
    measurementId: 'G-0YL0N9J2HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe5vaT7QOBEdtx1uhCNCO5ztxkJd5o2cg',
    appId: '1:939353486689:android:d2e6ab3a1492740ec0c120',
    messagingSenderId: '939353486689',
    projectId: 'prjpab2-si61-0036',
    storageBucket: 'prjpab2-si61-0036.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApD4LDLHwLCFhrycEHZd3KWoMNqRsB3hw',
    appId: '1:939353486689:ios:1d7f3593dde6b80ac0c120',
    messagingSenderId: '939353486689',
    projectId: 'prjpab2-si61-0036',
    storageBucket: 'prjpab2-si61-0036.firebasestorage.app',
    iosClientId: '939353486689-uc1hb86uevdjkjuv9v8rjdeekslapkan.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApD4LDLHwLCFhrycEHZd3KWoMNqRsB3hw',
    appId: '1:939353486689:ios:1d7f3593dde6b80ac0c120',
    messagingSenderId: '939353486689',
    projectId: 'prjpab2-si61-0036',
    storageBucket: 'prjpab2-si61-0036.firebasestorage.app',
    iosClientId: '939353486689-uc1hb86uevdjkjuv9v8rjdeekslapkan.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUotSKCurCowo5Hs1Wphu79VBUBySXGlI',
    appId: '1:939353486689:web:b0e7b408f2550f66c0c120',
    messagingSenderId: '939353486689',
    projectId: 'prjpab2-si61-0036',
    authDomain: 'prjpab2-si61-0036.firebaseapp.com',
    storageBucket: 'prjpab2-si61-0036.firebasestorage.app',
    measurementId: 'G-188RQDDD19',
  );

}